### PR TITLE
#1 Fix : Loading Spinner

### PR DESCRIPTION
**Pull request by AnshMehta24**
# Issue: #1
The loading spinner was occupying the entire screen and did not align well with the theme, impacting user experience.

# Fix:

### The ClipLoader is now only visible within the Output Editor, ensuring the spinner is limited to the relevant area.

### CODE REVIEW

**Review by aayushai — APPROVED** [review]

**Comment by AnshMehta24** [comment]
Preview:

https://github.com/user-attachments/assets/cf1be22a-bc19-4890-b098-2aff49d7bfab

## it's my first contribution, so I'd appreciate any feedback.

**Comment by aayushai** [comment]
**Nice job keep contributing to open-source.**

**Comment by AnshMehta24** [comment]
hey @aayushai , i  think you have not merged my whole code (Its becasue of Merge Conflicts). you can go through my code and check the preview i have commented it's looking good instead of whole screen gone black..

**Comment by aayushai** [comment]
Whole screen is not going black, only the output field has spinner contained.
check this link [https://transpiler-x.vercel.app/]

**Comment by AnshMehta24** [comment]
ohh I see. you just commited that Remaining code. because  from this pr you have changed only 2 lines that 's why im confused. 
now i have checked that you have added that remaining lines of code.

**Comment by aayushai** [comment]
Yeah, while merging conflicts it made an error so i had to do it.

**Comment by AnshMehta24** [comment]
got it!!

**Pull request merged**
