### PR TITLE
ISSUE #3  Fix: Input/Output Fields Vertically on Mobile View

### PR DESCRIPTION
**Pull request by syamjir**
Hi Aayushai

This pull request includes the following change:

Aligning the input and output fields vertically on mobile devices (up to 768px). For larger screens, the fields will automatically adjust to a horizontal alignment, providing an optimal user experience across different screen sizes.

Please review the changes and provide feedback.

### CODE REVIEW

**Comment by aayushai** [comment]
can you make changes in the updated code

**Comment by syamjir** [comment]
@aayushai ,Okay, I will pull the code, fix the alignment, and then send a pull request.

**Comment by aayushai** [comment]
It's been merged now, don't worry.

**Comment by syamjir** [comment]
> It's been merged now, don't worry.

ok aayushai.happy coding!

**Pull request closed without merging**
