### PR TITLE
Add prism.js styling

### LINKED ISSUE #22: Add Code Highlighting
# Add Code Highlighting to Output and Input

## Description:
Improve the readability of the output by adding syntax highlighting for the converted code. Use a library like **`Prism.js`** or **`Highlight.js`**.

### Action Items:
- Add syntax highlighting to the output code block.
- Ensure it matches the selected language (e.g., JavaScript, Python, etc.).

### Example Code:
```js
import Prism from 'prismjs';

<pre className="language-js">
  <code dangerouslySetInnerHTML={{ __html: Prism.highlight(outputCode, Prism.languages.javascript, 'javascript') }} />
</pre>
```
### Reference:
- Use Prism.js for language-based code highlighting.

### PR DESCRIPTION
**Pull request by peterdanwan**
Hello! This pull request is an attempt to fix #22 by adding a highlighted `input` field and highlighted `output` field using `prism.js`.

This is what the page looks like right now:

current-view

Please let me know if there are things that should be changed, or if you have any suggestions!

### CODE REVIEW

**Comment by peterdanwan** [comment]
Update: I found perhaps a better alternative to `prism.js`, called, [shiki](https://shiki.style/guide/). It seems to more easily integrate into the `Editor` component that was being used before.

Now, the result looks like this:

shiki

**Comment by aayushai** [comment]
Are you working on Shiki?

**Comment by peterdanwan** [comment]
Will do!

**Comment by aayushai** [comment]
yeah you can.

**Pull request closed without merging**
