### PR TITLE
feat: incorporate shiki syntax-styling with light and dark mode

### LINKED ISSUE #22: Add Code Highlighting
# Add Code Highlighting to Output and Input

## Description:
Improve the readability of the output by adding syntax highlighting for the converted code. Use a library like **`Prism.js`** or **`Highlight.js`**.

### Action Items:
- Add syntax highlighting to the output code block.
- Ensure it matches the selected language (e.g., JavaScript, Python, etc.).

### Example Code:
```js
import Prism from 'prismjs';

<pre className="language-js">
  <code dangerouslySetInnerHTML={{ __html: Prism.highlight(outputCode, Prism.languages.javascript, 'javascript') }} />
</pre>
```
### Reference:
- Use Prism.js for language-based code highlighting.

### LINKED ISSUE #34: Add Syntactic Code Highlighting with shiki.js
As discussed with @aayushai in this thread [here](https://github.com/aayushai/TranspilerX/issues/22#issuecomment-2408397243), this is another issue with regards to improving the `syntax highlighting` offered by the Monaco Editor's, `Editor` component. This will be achieved by using the [shiki](https://shiki.style/packages/monaco) library.

Please note that I will do this first, and create a separate issue with regards to adding a "Copy" button to the Input and Output Editors.

### PR DESCRIPTION
**Pull request by peterdanwan**
This fixes #34 and fixes #22 (NOTE: 22 is old).

With the recent additions made to `TranspilerX`, there is now a light mode and dark mode.

This pull request incorporates that by switching the theme of the `Editor` components to use `vitesse-dark` or `vitesse-light` depending if the user is on dark mode or light mode respectively.

This pull request also uses the proper `code formatting` as defined in `.vscode/settings.json` and `.prettierrc` (which results in a larger diff in the `src/CodeConverter.jsx` file due to the fix in formatting).

### CODE REVIEW

**Comment by aayushai** [comment]
I've just merged a PR can you update your commit with latest main branch code.

**Comment by peterdanwan** [comment]
Hello @aayushai! Rebased my commit on top of the recent change to main. Can you review it when you have a chance please?

**Comment by aayushai** [comment]
Hi @peterdanwan ,Code editor looks good but the Toastify alert is not there which was committed in the last PR merge.

**Comment by peterdanwan** [comment]
> Hi @peterdanwan ,Code editor looks good but the Toastify alert is not there which was committed in the last PR merge.

Hi @aayushai - just want to make sure I catch which toastify message I might have broken by accident.

From the last push I made, I see this particular toastify message when I try to press convert when there's no input code:

image

Is there another one that's missing now?

**Comment by aayushai** [comment]
This is what I am talking about instead of toastify its showing empty message on output editor.

Screenshot 2024-10-13 at 12 06 52 AM

**Comment by peterdanwan** [comment]
@aayushai Would it be possible for us to hop in a Discord Call? On my side, I can see the toastify message and my changes to the Editor component.

**Comment by aayushai** [comment]
Hi @peterdanwan ,
It's pretty late in my country, so a call is not possible now but I think if you make a new PR with the same commits I think it will solve the issue.

**Comment by peterdanwan** [comment]
> Hi @peterdanwan , It's pretty late in my country, so a call is not possible now but I think if you make a new PR with the same commits I think it will solve the issue.

Sounds good, going to make a new pr with a separate branch.

**Pull request closed without merging**
